# Release signing config (local only)
# storeFile is relative to the android/ folder (rootProject)
storeFile=qalbi-itmaan-release.jks
storePassword=Sdkmhmd1996@
keyAlias=qalbi_itmaan
keyPassword=Sdkmhmd1996@
