import Dexie, { type Table } from 'dexie';
import { BRAND } from './brand';

// Interfaces mirroring our Firestore data structures
export interface Product {
    id?: string;
    name: { fr: string; ar: string };
    category: string;
    price: number;
    cost: number;
    stock: number;
    minStock: number;
    sku: string;
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
}

export interface Service {
    id?: string;
    name: { fr: string; ar: string };
    category: string;
    price: number;
    duration: number; // minutes
    isActive: boolean;
    createdAt: Date;
    updatedAt: Date;
}

export interface Customer {
    id?: string;
    name: string;
    phone: string;
    email?: string;
    notes?: string;
    totalVisits: number;
    totalSpent: number;
    lastVisit?: Date;
    createdAt: Date;
    updatedAt: Date;
}

export interface Sale {
    id?: string;
    items: any[];
    subtotal: number;
    totalDiscount: number;
    total: number;
    paymentMethod: 'cash' | 'card';
    customerId?: string;
    customerName?: string;
    staffId?: string;
    status: 'completed' | 'cancelled';
    createdAt: Date;
    updatedAt: Date;
}

export class QalbiDatabase extends Dexie {
    products!: Table<Product>;
    services!: Table<Service>;
    customers!: Table<Customer>;
    transactions!: Table<Sale>;
    staff!: Table<any>;
    settings!: Table<any>;
    stockMovements!: Table<any>;
    locations!: Table<any>;
    hrTasks!: Table<any>;
    leaves!: Table<any>;
    // Add other tables as needed

    constructor() {
        super(BRAND.dbName);

        // Define tables and indexes
        // 'id' is primary key (auto-generated if we use ++id, but we might want UUIDs to match Firebase style)
        // For sync simplicity, using UUIDs generated by client is better than auto-increment numbers.
        // We defined 'id' as string in interfaces.
        this.version(1).stores({
            products: 'id, sku, category, isActive',
            services: 'id, category, isActive',
            customers: 'id, phone, name',
            transactions: 'id, customerId, status, createdAt',
            staff: 'id, email, role, isActive',
            settings: 'id, category',
            stockMovements: 'id, productId, type, date'
        });

        // Version 2: Add reservations table
        this.version(2).stores({
            reservations: 'id, date, status, staffId'
        });

        // Version 3: Add HR tables (attendance, leaves)
        this.version(3).stores({
            attendance: 'id, staffId, date, status',
            leaves: 'id, staffId, status, startDate'
        });

        // Version 4: Add audit logs and inscriptions
        this.version(4).stores({
            auditLogs: 'id, userId, action, collection, timestamp',
            inscriptions: 'id, trackingNumber, customerPhone, status, createdAt'
        });

        // Version 5: Add locations table (room/space bookings)
        this.version(5).stores({
            locations: 'id, date, startDate, endDate, room, status, customerName'
        });

        // Version 6: Add Missing tables
        this.version(6).stores({
            hrTasks: 'id, assignedTo, status, priority, dueDate',
            sessions: 'id, formationId, startDate, status',
            materialMovements: 'id, type, date, status'
        });

        // Version 7: Add Shop E-Commerce tables
        this.version(7).stores({
            laptops: 'id, brand, category, price, stock',
            pieces: 'id, brand, category, price, stock',
            invoices: 'id, customerName, status, dateStr',
            orders: 'id, customerName, status, dateStr',
            customers: 'id, phone, name, email'
        });

        // Version 8: Add POS transaction history tables for laptops & pieces
        this.version(8).stores({
            transactions_laptops: 'id, customerName, status, dateStr',
            transactions_pieces: 'id, customerName, status, dateStr'
        });

        // Version 9: Add repairs / SAV table
        this.version(9).stores({
            repairs: 'id, customerName, customerPhone, status, depositDate, trackingCode'
        });
    }
}

export const db = new QalbiDatabase();

// Handle version upgrade failures gracefully
db.on('blocked', () => {
    console.warn('[LOCAL_DB] Database upgrade blocked by another tab. Please close other tabs and refresh.');
});

db.open().catch(err => {
    console.error('[LOCAL_DB] Failed to open database, attempting recovery:', err);
    // If the database can't be opened (version conflict), delete and recreate
    db.delete().then(() => {
        console.log('[LOCAL_DB] Deleted old database, reloading...');
        window.location.reload();
    }).catch(delErr => {
        console.error('[LOCAL_DB] Could not delete database:', delErr);
    });
});

/**
 * Create a staff record in local Dexie database
 * Used when Firebase is not configured
 */
export const createLocalStaff = async (staffData: {
    id: string;
    authUid: string;
    email: string;
    name: string;
    role: string;
    phone?: string;
    commissionRate?: number;
    isActive: boolean;
    mustChangePassword?: boolean;
    isLocal?: boolean;
    needsSync?: boolean;
    createdAt?: Date;
    updatedAt?: Date;
}): Promise<string> => {
    const now = new Date();
    const record = {
        ...staffData,
        createdAt: staffData.createdAt || now,
        updatedAt: staffData.updatedAt || now,
    };
    await db.staff.put(record);
    console.log('[LOCAL_DB] Created local staff record:', record.id);
    return record.id;
};

/**
 * Purge all local Dexie tables and record local wipe timestamp
 */
export async function purgeAllLocalData(): Promise<void> {
    try {
        const tableNames = [
            'products', 'services', 'customers', 'transactions', 'staff', 'settings',
            'stockMovements', 'reservations', 'attendance', 'leaves', 'auditLogs',
            'inscriptions', 'locations', 'hrTasks', 'sessions', 'materialMovements',
            'laptops', 'pieces', 'invoices', 'orders', 'transactions_laptops',
            'transactions_pieces', 'repairs'
        ];
        for (const name of tableNames) {
            try {
                const table = (db as any)[name];
                if (table && typeof table.clear === 'function') {
                    await table.clear();
                }
            } catch (e) {
                console.warn(`[LOCAL_DB] Notice clearing table ${name}:`, e);
            }
        }
        localStorage.setItem('nhtech_last_wipe_timestamp', String(Date.now()));
        console.log('[LOCAL_DB] All local Dexie tables cleared.');
    } catch (err) {
        console.warn('[LOCAL_DB] Error purging local database:', err);
    }
}
